<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GiftcardsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('giftcards')->delete();
        
        \DB::table('giftcards')->insert(array (
            0 => 
            array (
                'id' => 1,
                'comprado_por' => 1,
                'beneficiador_id' => 2,
                'trabajador_id' => 1,
                'promocion_id' => 1,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-11-01',
                'fecha_expiracion' => '2025-01-01',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-07 22:27:21',
                'updated_at' => '2024-12-09 01:09:52',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 4,
                'comprado_por' => 2,
                'beneficiador_id' => 12,
                'trabajador_id' => 12,
                'promocion_id' => 1,
                'valor' => '25000.00',
                'mensaje_personalizado' => 'Disfruta esta promoción especial.',
                'fecha_compra' => '2024-12-01',
                'fecha_expiracion' => '2025-02-01',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-08 19:15:17',
                'updated_at' => '2024-12-09 01:09:22',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 5,
                'comprado_por' => 3,
                'beneficiador_id' => 4,
                'trabajador_id' => 13,
                'promocion_id' => 3,
                'valor' => '50000.00',
                'mensaje_personalizado' => 'Con cariño para ti.',
                'fecha_compra' => '2024-12-02',
                'fecha_expiracion' => '2025-02-02',
                'fecha_cobro' => '2024-12-15',
                'estatus_giftcard' => 'cobrada',
                'created_at' => '2024-12-08 19:15:17',
                'updated_at' => '2024-12-09 01:52:38',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 6,
                'comprado_por' => 4,
                'beneficiador_id' => 5,
                'trabajador_id' => 14,
                'promocion_id' => 6,
                'valor' => '18000.00',
                'mensaje_personalizado' => 'Un obsequio para disfrutar.',
                'fecha_compra' => '2024-11-25',
                'fecha_expiracion' => '2025-01-25',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'por_expirar',
                'created_at' => '2024-12-08 19:15:17',
                'updated_at' => '2024-12-09 01:30:09',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 7,
                'comprado_por' => 6,
                'beneficiador_id' => 7,
                'trabajador_id' => 15,
                'promocion_id' => 9,
                'valor' => '35000.00',
                'mensaje_personalizado' => 'Felices Fiestas.',
                'fecha_compra' => '2024-12-03',
                'fecha_expiracion' => '2025-02-03',
                'fecha_cobro' => '2024-12-08',
                'estatus_giftcard' => 'cobrada',
                'created_at' => '2024-12-08 19:15:17',
                'updated_at' => '2024-12-09 01:46:45',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 8,
                'comprado_por' => 9,
                'beneficiador_id' => 11,
                'trabajador_id' => 17,
                'promocion_id' => 4,
                'valor' => '45000.00',
                'mensaje_personalizado' => 'Un regalo inolvidable.',
                'fecha_compra' => '2024-12-04',
                'fecha_expiracion' => '2025-02-04',
                'fecha_cobro' => '2024-12-20',
                'estatus_giftcard' => 'cobrada',
                'created_at' => '2024-12-08 19:15:17',
                'updated_at' => '2024-12-09 01:59:07',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 9,
                'comprado_por' => 5,
                'beneficiador_id' => 4,
                'trabajador_id' => 2,
                'promocion_id' => 9,
                'valor' => '20000.00',
                'mensaje_personalizado' => 'feliz cumpleaños!',
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:24:23',
                'updated_at' => '2024-12-09 12:24:23',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 10,
                'comprado_por' => 1,
                'beneficiador_id' => 5,
                'trabajador_id' => 2,
                'promocion_id' => 10,
                'valor' => '20000.00',
                'mensaje_personalizado' => 'Para que tengas una mejor alimentación!',
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:28:14',
                'updated_at' => '2024-12-09 12:28:14',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 11,
                'comprado_por' => 6,
                'beneficiador_id' => 15,
                'trabajador_id' => 2,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => 'Para que tengas un buen balance nutricional!',
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:32:17',
                'updated_at' => '2024-12-09 12:32:17',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 12,
                'comprado_por' => 2,
                'beneficiador_id' => 3,
                'trabajador_id' => 14,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:48:27',
                'updated_at' => '2024-12-09 12:48:27',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 13,
                'comprado_por' => 2,
                'beneficiador_id' => 3,
                'trabajador_id' => 14,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:51:14',
                'updated_at' => '2024-12-09 12:51:14',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 14,
                'comprado_por' => 2,
                'beneficiador_id' => 3,
                'trabajador_id' => 14,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:51:17',
                'updated_at' => '2024-12-09 12:51:17',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 15,
                'comprado_por' => 2,
                'beneficiador_id' => 3,
                'trabajador_id' => 14,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:51:19',
                'updated_at' => '2024-12-09 12:51:19',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'comprado_por' => 2,
                'beneficiador_id' => 1,
                'trabajador_id' => 1,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:51:35',
                'updated_at' => '2024-12-09 12:51:35',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 17,
                'comprado_por' => 2,
                'beneficiador_id' => 1,
                'trabajador_id' => 1,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:51:42',
                'updated_at' => '2024-12-09 12:51:42',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 18,
                'comprado_por' => 2,
                'beneficiador_id' => 1,
                'trabajador_id' => 1,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:51:50',
                'updated_at' => '2024-12-09 12:51:50',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 19,
                'comprado_por' => 2,
                'beneficiador_id' => 1,
                'trabajador_id' => 1,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:51:53',
                'updated_at' => '2024-12-09 12:51:53',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 20,
                'comprado_por' => 2,
                'beneficiador_id' => 1,
                'trabajador_id' => 1,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:52:03',
                'updated_at' => '2024-12-09 12:52:03',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 21,
                'comprado_por' => 2,
                'beneficiador_id' => 1,
                'trabajador_id' => 1,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 12:52:08',
                'updated_at' => '2024-12-09 13:15:35',
                'deleted_at' => '2024-12-09 13:15:35',
            ),
            19 => 
            array (
                'id' => 22,
                'comprado_por' => 5,
                'beneficiador_id' => 2,
                'trabajador_id' => 2,
                'promocion_id' => 10,
                'valor' => '10000.00',
                'mensaje_personalizado' => NULL,
                'fecha_compra' => '2024-12-09',
                'fecha_expiracion' => '2025-02-09',
                'fecha_cobro' => NULL,
                'estatus_giftcard' => 'activa',
                'created_at' => '2024-12-09 13:01:20',
                'updated_at' => '2024-12-09 13:15:17',
                'deleted_at' => '2024-12-09 13:15:17',
            ),
        ));
        
        
    }
}