import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel([
            'resources/js/fichas/create.js',
            'resources/js/giftcard/giftcard-modal.js',
            'resources/js/giftcard/giftcard.js',
            'resources/js/global/alert.js',
            'resources/js/global/app.js',
            'resources/js/global/bootstrap.js',
            'resources/js/global/botones.js',
            'resources/js/global/checkbox.js',
            'resources/js/global/email.js',
            'resources/js/global/input.js',
            'resources/js/global/modal.js',
            'resources/js/global/paginacion.js',
            'resources/js/global/radios.js',
            'resources/js/global/sidebar.js',
            'resources/js/global/tabla.js',
            'resources/js/global/utilidades.js',
            'resources/js/home/animated-background.js',
            'resources/js/home/home.js',
            'resources/js/pacientes/create.js',
            'resources/js/pacientes/filtro.js',
            'resources/js/pacientes/pacientes.js',
            'resources/js/reservas/reservas.js',
            'resources/js/servicios/create.js',
            'resources/js/servicios/servicios.js',
            'resources/css/giftcard/giftcard.css',
            'resources/css/global/alert.css',
            'resources/css/global/app.css',
            'resources/css/global/botones.css',
            'resources/css/global/checkbox.css',
            'resources/css/global/email.css',
            'resources/css/global/input.css',
            'resources/css/global/modal.css',
            'resources/css/global/module.css',
            'resources/css/global/radios.css',
            'resources/css/global/root.css',
            'resources/css/global/sidebar.css',
            'resources/css/global/tabla.css',
            'resources/css/home/animated-background.css',
            'resources/css/home/home.css',
            'resources/css/pacientes/create.css',
            'resources/css/pacientes/filtro.css',
            'resources/css/pacientes/pacientes.css',
            'resources/css/reservas/reservas.css',
            'resources/css/servicios/create.css',
            'resources/css/servicios/servicios.css'
        ]),
    ],
});